[app]
title = 战利品价格查询
package.name = darkprice
package.domain = org.darkprice
source.main = dadPriceInquiry.py
source.dir = .
source.include_exts = py,png,json
version = 1.0
version.code = 1
icon.filename = icon.png
requirements = python3==3.12.7,kivy==2.2.1,certifi,chardet,idna,urllib3,requests
android.permissions = INTERNET,ACCESS_NETWORK_STATE
orientation = portrait
fullscreen = 0
android.minapi = 23
android.api = 33
android.archs = arm64-v8a
android.ndk = 25c
android.build_tools = "33.0.2"
output_dir = bin
debug = 0
p4a.source_dir = ./.buildozer/android/platform/python-for-android
android.accept_sdk_license = True
p4a.force_build = True